### ISSUE TITLE
tutorial vs repo confusion

### ISSUE THREAD

**Issue by bmm-brobbins** [markerikson/redux-quickstart-example-app#33]
Hi, newbie here trying to follow along with the tutorial at https://redux.js.org/tutorials/essentials/part-3-data-flow, which links to this repo.

Probably I'm confused, but I thought the completed tutorial would mirror the 'tutorial-steps' branch of this repo (as well as the linked sandbox at https://codesandbox.io/s/github/reduxjs/redux-essentials-example-app/tree/tutorial-steps)?

But I don't see, for example, the file 'features/posts/postsSlice.js' in this repo, while it's referenced early and often in the tutorial.

Please help clarify my confusion.  Thank you.

**Comment by markerikson** [comment]
Hiya. I _may_ have an explanation for the confusion :)

Each page in the "Essentials" tutorial starting with page 3 has its own CodeSandbox at the end (so, pages 3-8).  Each of those sandboxes points to a specific tagged commit in this repo, and the entire `tutorial-steps` branch shows _allllll_ of the commits that I made over the course of writing the tutorial application.

However, if you just look at the `tutorial-steps` branch by itself... what you're seeing is the code as it exists _at the very end of Part 8_ :)  And since Part 7 and Part 8 drastically change the code to show how RTK Query works, at that point `postsSlice` pretty much goes away.

So, if you look at the earlier commits, and tags like https://github.com/reduxjs/redux-essentials-example-app/tree/checkpoint-3-postRequests, the `postsSlice.js` file definitely exists: https://github.com/reduxjs/redux-essentials-example-app/blob/checkpoint-3-postRequests/src/features/posts/postsSlice.js .

**Comment by bmm-brobbins** [comment]
Thank you for the quick reply.  If I had been more patient and continued powering through the tutorial, I might have noticed those steps :)  And I'm glad RTK Query gets invoked.  Thanks for clarifying!

**Comment by markerikson** [comment]
You're welcome!  And I could probably tweak the wording on each page to be a bit more clear about where to find that code.
